### ISSUE TITLE
request.ipinfo.ip return the server public ip  instead of the client public ip

### ISSUE THREAD

**Issue by LacErnest** [ipinfo/django#31]
Hi,
since your update to 2.0.0, the request.ipinfo.ip returns the server public IP instead of the client public IP.
what should I do to get the client public IP like before instead of the server public id?
I really like your API. You are doing an amazing job.

Best regards.

**Comment by UmanShahzad** [comment]
@LacErnest thanks a ton for using our API!

Currently the algorithm by default is as follows:

```python
        x_forwarded_for = request.META.get(HTTP_X_FORWARDED_FOR)
        if x_forwarded_for:
            return x_forwarded_for.split(",")[0]
        return request.META.get(REMOTE_ADDR)
```

This gets things from the `X-Forwarded-For` HTTP header so that we don't select the IP of the proxy server in front of you if you have one, instead opting for the originating client IP.

If for some reason this doesn't fit your use case you can see https://github.com/ipinfo/django#ip-selection-mechanism to fully control it in the latest version of this SDK.
